### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Cannot find module 'bonjour'

### ISSUE THREAD

**Issue by vespino** [oznu/homebridge-gsh#107]
I have updated all to 1.3.4 and my Homebridge Google Smart Home to 2.1.0 and everything seems to be running fine but the following error shows in the logs screen:

UnhandledPromiseRejectionWarning: Error: Cannot find module 'bonjour'

Continuing:

Require stack:
- /usr/lib/node_modules/homebridge-gsh/node_modules/hap-node-client/HAPNodeJSClient.js
- /usr/lib/node_modules/homebridge-gsh/dist/hap.js
- /usr/lib/node_modules/homebridge-gsh/dist/main.js
- /usr/lib/node_modules/homebridge-gsh/dist/platform.js
- /usr/lib/node_modules/homebridge-gsh/dist/index.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-gsh/node_modules/hap-node-client/HAPNodeJSClient.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7790) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Anything I can/should do about these errors? Before updating the plugin there were no errors btw.

**Comment by rodymary** [comment]
Same after upgrading to last homebridge-gsh@**2.1.0**
Had to downgrade : sudo -E -n npm install -g homebridge-gsh@**2.0.1**
Hope it will help

**Comment by CyberSnek** [comment]
Reverting to 2.0.1 resolved this issue for me.
