### ISSUE TITLE
Homebridge GSH crashing every few minutes.

### ISSUE THREAD

**Issue by Niydzhu** [oznu/homebridge-gsh#133]
**Describe The Bug:**

Homebridge GSH crashing every few minutes.
Sometimes I can interact with the devices but soon after, it will crash.

**To Reproduce:**

Connect homebridge to Google Home.

**Expected behavior:**

Ability to interact with the homebridge devices.

**Logs:**

```
TypeError: Cannot read properties of undefined (reading 'value')
    at Lightbulb.query (/usr/lib/node_modules/homebridge-gsh/src/types/lightbulb.ts:77:94)
    at Hap.<anonymous> (/usr/lib/node_modules/homebridge-gsh/src/hap.ts:500:66)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-gsh/dist/hap.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-gsh/dist/hap.js:23:12)
    at Hap.sendFullStateReport (/usr/lib/node_modules/homebridge-gsh/dist/hap.js:414:16)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-gsh/src/main.ts:71:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
[05/11/2021, 15:08:00] Got SIGTERM, shutting down Homebridge...
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge 375B",
        "username": "0E:CE:3C:1C:37:5B",
        "port": 51363,
        "pin": "982-63-517"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode-purple",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Govee",
            "username": "xxxxxx",
            "password": "xxxxxx",
            "platform": "Govee"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxxxx",
                "password": "xxxxx",
                "countryCode": "33",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        },
        {
            "name": "Google Smart Home",
            "token": "xxx",
            "notice": "Keep your token a secret!",
            "platform": "google-smarthome"
        }
    ]
}
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v16.13.0
* **NPM Version**: 8.1.0
* **Homebridge Version**: 1.3.5
* **Homebridge GSH Plugin Version**: v2.2.0
* **Homebridge Config UI X Plugin Version**:
* **Operating System**: Raspberry pi OS lite

**Comment by Niydzhu** [comment]
Found the solution : The issue was I needed an API key for homebridge-govee to work properly.
Not a problem with homebridge-gsh.

**Comment by dacbreakpoint** [comment]
I run into the same issue. My API-key is appropriately set, and I can turn the device on-/off, but it will produce this error and crashes the whole application.

I figured out that the saturation characteristic is `undefined` in my case, and because it accesses the `.value` property, it will crash.

[`saturation: service.characteristics.find(x => x.type === Characteristic.Saturation).value / 100`](https://github.com/oznu/homebridge-gsh/blob/master/src/types/lightbulb.ts#L77)
