### ISSUE TITLE
plugin is randomly crashing with: Cannot read properties of undefined (reading 'uniqueId')

### ISSUE THREAD

**Issue by duculete** [oznu/homebridge-gsh#209]
```
TypeError: Cannot read properties of undefined (reading 'uniqueId')
    at Hap.<anonymous> (/homebridge/node_modules/homebridge-gsh/src/hap.ts:485:22)
    at Generator.next (<anonymous>)
    at /homebridge/node_modules/homebridge-gsh/dist/hap.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/homebridge/node_modules/homebridge-gsh/dist/hap.js:23:12)
    at Hap.processPendingStateReports (/homebridge/node_modules/homebridge-gsh/dist/hap.js:404:16)
    at SafeSubscriber._next (/homebridge/node_modules/homebridge-gsh/src/hap.ts:118:14)
    at SafeSubscriber.__tryOrUnsub (/homebridge/node_modules/homebridge-gsh/node_modules/rxjs/src/internal/Subscriber.ts:265:10)
    at SafeSubscriber.next (/homebridge/node_modules/homebridge-gsh/node_modules/rxjs/src/internal/Subscriber.ts:207:14)
    at Subscriber._next (/homebridge/node_modules/homebridge-gsh/node_modules/rxjs/src/internal/Subscriber.ts:139:22)
```

Homebridge v1.8.3 (HAP v0.12.2)
OS: Linux 6.6.28+rpt-rpi-v8 arm64
Node.js v20.15.0 /opt/homebridge/bin/node

**Comment by duculete** [comment]
after this error, all goole home accessories from HB are removed
