### ISSUE TITLE
Multi-Instance Support

### ISSUE THREAD

**Issue by meluvalli** [oznu/homebridge-gsh#26]
I am running two instances of HomeBridge on my server.  

Would be nice to force homebridge-gsh to only look at the one running instance (Bind to specific port).

I receive errors because it's trying to access my other instance.

<pre>
[12/20/2019, 4:26:34 AM] [Google Smart Home] Error: Homebridge auth failed, invalid PIN [_Pin from second Instance_]
    at HAPNodeJSClient.<anonymous> (C:\HomeBridge\node_modules\homebridge-gsh\node_modules\hap-node-client\HAPNodeJSClient.js:277:18)
    at eventedHttpClient.f [as callback] (C:\HomeBridge\node_modules\homebridge-gsh\node_modules\once\once.js:25:25)
    at Socket.<anonymous> (C:\HomeBridge\node_modules\homebridge-gsh\node_modules\hap-node-client\lib\eventedHttpClient.js:71:16)
    at Socket.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at Socket.Readable.push (_stream_readable.js:250:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
</pre>

**Comment by oznu** [comment]
Add the username of the instance (from the other config.json) to the blacklist).

![image](https://user-images.githubusercontent.com/3979615/71314614-a2ec0c00-249f-11ea-8ce8-c87c0e3a33ab.png)
