### ISSUE TITLE
Cannot get switch state in Google Home App

### ISSUE THREAD

**Issue by fizulnizam** [oznu/homebridge-gsh#51]
I use this plugin with HOOBS, and installed it correctly like how the installation process mentioned, but when I go into the Google Home App on my phone and press of the appliance that I have which runs on the Broadlink RM Mini 3, my HOOBS crashes.

**To Reproduce:**
Go into the Google Home app, press on one of the accessory that is controlled by a Broadlink RM Mini 3, check hoobs.local for log and status.

**Expected behavior:**
I can see whether the accessory is on or off.

**Logs:**

```
[Google Smart Home] Received QUERY intent
30/05/2020, 18:54:22 TypeError: log is not a function
    at Name.getName (/home/hoobs/.hoobs/node_modules/homebridge-platform-helper/dist/serviceManager.js:69:9)
    at Name.emit (events.js:223:5)
    at Name.EventEmitter.emit (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at Name.Characteristic._this.getValue (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Characteristic.js:190:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:753:32
    at Array.forEach (<anonymous>:null:null)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:694:18)
    at HAPServer.emit (events.js:223:5)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:664:23)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:227:39)
    at IncomingMessage.emit (events.js:223:5)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
30/05/2020, 18:54:22 Got SIGTERM, shutting down Bridge...
30/05/2020, 18:54:22 (node:29250) UnhandledPromiseRejectionWarning: Error: socket hang up
30/05/2020, 18:54:22 at connResetException (internal/errors.js:570:14)
30/05/2020, 18:54:22 at Socket.socketOnEnd (_http_client.js:440:23)
30/05/2020, 18:54:22 at Socket.emit (events.js:228:7)
30/05/2020, 18:54:22 at endReadableNT (_stream_readable.js:1185:12)
30/05/2020, 18:54:22 at processTicksAndRejections (internal/process/task_queues.js:81:21)
30/05/2020, 18:54:22 (node:29250) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
30/05/2020, 18:54:22 (node:29250) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
30/05/2020, 18:54:41 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/05/2020, 18:54:41 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/05/2020, 18:54:41 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/05/2020, 18:54:41 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/05/2020, 18:54:41 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/05/2020, 18:54:41 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
30/05/2020, 18:54:41 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826

```

**Homebridge Config:**

{
            "platform": "google-smarthome",
            "plugin_map": {
                "plugin_name": "homebridge-gsh"
            },
            "name": "Google Smart Home",
            "notice": "Keep your token a secret!",
            "token": "meowmeow",
            "debug": false,
            "instanceBlacklist": [],
            "accessoryFilter": []
        }

**Environment:**

* **Node.js Version**: 12.14.1
* **NPM Version**: 
* **HOOBS Version**: 3.2.6
* **Homebridge GSH Plugin Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**: HOOBS

**Comment by oznu** [comment]
Hello @fizulnizam,

Can you replicate this issue on a standard Homebridge installation?

**Comment by fizulnizam** [comment]
Hi oznu, I am sorry but I only have one device running HOOBS and no spare device to run Homebridge separately to test if the issue is the same or not on a standard Homebridge installation...

**Comment by oznu** [comment]
Hi @fizulnizam, 
You will need to raise the issue with their support team.
