### ISSUE TITLE
Errors in hap.js

### ISSUE THREAD

**Issue by madchicken** [oznu/homebridge-gsh#69]
**Describe The Bug:**
When updating values through the `updateCharacteristic` on local thermostat+dehumidifier accessory, I see errors in logs. If I am performing the action through a scene, the whole scene application fails.

**To Reproduce:**
You need an accessory that exposes both thermostat and dehumidifier, then update some characteristic.

**Expected behavior:**
No error should be reported in logs

**Logs:**
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'characteristics' of undefined
    at Hap.<anonymous> (/usr/local/lib/node_modules/homebridge-gsh/src/hap.ts:452:38)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-gsh/dist/hap.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-gsh/dist/hap.js:4:12)
    at Hap.handleHapEvent (/usr/local/lib/node_modules/homebridge-gsh/dist/hap.js:360:16)
    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-gsh/src/hap.ts:140:12)
    at HAPNodeJSClient.emit (events.js:310:20)
    at HAPNodeJSClient.EventEmitter.emit (domain.js:482:12)
    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-gsh/node_modules/hap-node-client/HAPNodeJSClient.js:97:10)
```

**Homebridge Config:**

```json
        {
            "name": "Google Smart Home",
            "token": "****",
            "notice": "Keep your token a secret!",
            "platform": "google-smarthome"
        }
```

**Environment:**

* **Node.js Version**: 12.16.3
* **NPM Version**: 6.14.7
* **Homebridge Version**: 1.2.0-beta.35 and 1.1.2
* **Homebridge GSH Plugin Version**: 1.6.0
* **Homebridge Config UI X Plugin Version**: 4.26.0
* **Operating System**: Raspbian

**Comment by speedyuy** [comment]
I also have a thermostat and I am getting a very similar error.
No dehumidifier, only thermostat. When I start Homebride I don't get any errors when the thermostat updates characteristics. After a while it start giving this error:

```
(node:5612) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'characteristics' of undefined
    at Hap.<anonymous> (C:\Users\Usuario\AppData\Roaming\npm\node_modules\homebridge-gsh\src\hap.ts:452:38)
    at Generator.next (<anonymous>)
    at C:\Users\Usuario\AppData\Roaming\npm\node_modules\homebridge-gsh\dist\hap.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Usuario\AppData\Roaming\npm\node_modules\homebridge-gsh\dist\hap.js:4:12)
    at Hap.handleHapEvent (C:\Users\Usuario\AppData\Roaming\npm\node_modules\homebridge-gsh\dist\hap.js:360:16)
    at HAPNodeJSClient.<anonymous> (C:\Users\Usuario\AppData\Roaming\npm\node_modules\homebridge-gsh\src\hap.ts:140:12)
    at HAPNodeJSClient.emit (events.js:315:20)
    at HAPNodeJSClient.<anonymous> (C:\Users\Usuario\AppData\Roaming\npm\node_modules\homebridge-gsh\node_modules\hap-node-client\HAPNodeJSClient.js:97:10)
    at EventEmitter.emit (events.js:315:20)
(node:5612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9619)
```

Did you fix the problem @madchicken ?
Thanks!

**Comment by madchicken** [comment]
@speedyuy No, I didn't. I could open a basic PR to skip the processing of the event if no service was found, but I'd like to understand why we get this error instead of simply muting it.

**Comment by speedyuy** [comment]
@madchicken Is it possible it is related to the characteristics implemented? In my thermostat I have only the required implemented:
CurrentHeatingCoolingState - TargetHeatingCoolingState - CurrentTemperature - TargetTemperature - TemperatureDisplayUnits

Optional Characteristics (NOT IMPLEMENTED in my thermostat)
CurrentRelativeHumidity - TargetRelativeHumidity - CoolingThresholdTemperature - HeatingThresholdTemperature

I too would like to find the error but have very little experience debugging Node code. I mainly use Console.log in my code.
I will try implementing all optional characteristics and see if this removes the error.

**Comment by oznu** [comment]
Should be fixed in the next release. tHank you for reporting.
